### ISSUE TITLE
Lentidão no funcionamento do plug-in

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/bibliographic-wp-plugin#10]
Provavelmente seja um problema de performance na API do FI-Admin, tendo em vista a quantidade de registros bibliográficos.

Verificar trace log do mysql.

**Comment by viniciusandrade** [comment]
Foi realizado a otimização do índice de consulta (solr/lucene) e também instalado o plugin wp super cache para tentar melhorar a performance do site.

**Comment by viniciusandrade** [comment]
Novos testes usando as ferramentas GTMetrix e Pingdom indicam que o site talvez não esteja sendo carregado fora do Brasil ou apresentando muita lentida.

Será realizado o teste de desabilitar o plugin para identificar se mesmo assim a instância apresenta lentidão e caso o problema persista será solicitado a migração do site para outro servidor.

**Comment by viniciusandrade** [comment]
Foi realizado a instalação do plugin em outro servidor e não foi identificado problemas de performance indicando que o problema deve ser realmente relacionado a infraestrutura, foi solicitado a migração da instância para para outro servidor.
