### ISSUE TITLE
Mudar banner do RedeTSA

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/bibliographic-wp-plugin#12]
Manter somente o logo do RedeTSA e acrescentar os logos da OPS/OMS

**Comment by renatomurasaki** [comment]
@pierrima por favor, proponer un banner para este sitio? Debe mantener la responsividad ya existente del sistema.

**Comment by pierrima** [comment]
@renatomurasaki Segue a proposta:

![banner](https://user-images.githubusercontent.com/13052947/29227614-e0c69662-7eac-11e7-87ce-4e2e8ecce915.jpg)

**Comment by renatomurasaki** [comment]
Marina, es necesario tener el logo de OPS/OMS también en el logo. Gracias!!

**Comment by pierrima** [comment]
@renatomurasaki  Sigue el banner con el logo

![banner](https://user-images.githubusercontent.com/13052947/29228788-a4bf0564-7eb1-11e7-93ad-c65ad5d7f0be.jpg)

**Comment by renatomurasaki** [comment]
Gracias! Esperando aprobación del equipo en WDC.

Renato

**Comment by viniciusandrade** [comment]
Atualizado no portal para facilitar a avaliação.
