### ISSUE TITLE
Definir nome para o site

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/bibliographic-wp-plugin#14]
Será convocado um comitê com representantes da Rede para definir o nome

**Comment by renatomurasaki** [comment]
ES - Base Regional de Informes de Evaluación de Tecnologías en Salud de las Américas 

PT - Base Regional de Informes de Avaliação de Tecnologias em Saúde das Américas

EN - Regional Base of Health Technology Assessment Reports of the Americas

FR  - Base Régionale des Rapports d'évaluation des technologies de la santé des Amériques

**Comment by viniciusandrade** [comment]
Ajuste realizado nos ajustes gerais do site e traduções aplicadas no Polylang
