### ISSUE TITLE
Acrescentar Termos de Uso no rodapé do portal

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/bibliographic-wp-plugin#16]

**Comment by renatomurasaki** [comment]
Poner en el pie de página el texto "Termos e condições de uso RedeTSA", apuntando para una página del WP. Tener en cuenta el idioma.

**Comment by viniciusandrade** [comment]
Páginas criadas (sem conteúdo) no WP e disponibilizado no rodapé do site:

http://sites.bvsalud.org/redetsa/pt/repositorio/
