### ISSUE TITLE
Desenvolver novo banner

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/bibliographic-wp-plugin#31]
O nome do repositorio será BRISA. Francisco enviará nome completo. O novo banner deve ter dois componentes: logo RedETSA, com link para o site redetsa.org, logo BRISA com o seu nome completo e logo OPAS/OMS e BIREME. O banner precisa se resolver nos dispositivos móveis.

**Comment by renatomurasaki** [comment]
Nome completo disponível em #14

**Comment by pierrima** [comment]
Segue a proposta com a alteração da cor do logo BRISA

![banner_prop2](https://user-images.githubusercontent.com/13052947/32289086-f6d0e04c-bf1c-11e7-82be-08a46b98dba3.jpg)

**Comment by pierrima** [comment]
Segue a proposta com as modificações solicitas
![banner_prop3](https://user-images.githubusercontent.com/13052947/32495321-5b07281c-c3ac-11e7-98ed-ebf30fed1b0c.jpg)

**Comment by pierrima** [comment]
![logo_brisa](https://user-images.githubusercontent.com/13052947/32510962-88075882-c3d9-11e7-8a9c-056abd3a21a2.jpg)

**Comment by viniciusandrade** [comment]
@renatomurasaki 

Foi substituído o banner no portal. Seria importante validar se o banner esta OK para que seja realizado a tradução do mesmo para os demais idiomas.

http://sites.bvsalud.org/redetsa/pt/repositorio/

[]s

**Comment by renatomurasaki** [comment]
Está OK. Já recebemos feedback da contraparte.

Renato

**Comment by renatomurasaki** [comment]
Necessário ajustar responsividade. No iPhone o banner não se ajusta.

Renato

**Comment by renatomurasaki** [comment]
@pierrima Nome completo da BIREME em francês:

Centre d’Information des Sciences de la Santé d'Amérique latine et des Caraïbes
