### ISSUE TITLE
Mudança no breadcrumb - link Inicio

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/bibliographic-wp-plugin#32]
O link Início em português, Accueil em francês, Inicio em espanhol e Home em inglês precisa apontar para o link redetsa.org, de acordo com os seguintes idiomas:

PT - http://redetsa.org/wp/?page_id=134
ES - http://redetsa.org/wp/?page_id=402
EN - http://redetsa.org/wp/?page_id=209
FR - http://redetsa.org/wp/?page_id=209 (es mismo del EN)

**Comment by viniciusandrade** [comment]
Adicionado opção de configuração da url da home nos diferentes idiomas na tela de ajustes do plugin e configurado na instância da redetsa.
