### ISSUE TITLE
Separar do banner da BRISA o logo da RedETSA

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/bibliographic-wp-plugin#37]
Colocar no logo da RedETSA o link para

PT - http://redetsa.org/wp/?page_id=134
ES - http://redetsa.org/wp/?page_id=402
EN - http://redetsa.org/wp/?page_id=209
FR - http://redetsa.org/wp/?page_id=209

**Comment by pierrima** [comment]
Links publicados
