### ISSUE TITLE
Há duplicação na visualização dos assuntos utilizados na indexação dos documentos

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/bibliographic-wp-plugin#40]
Exemplo - http://sites.bvsalud.org/redetsa/pt/brisa/resource/?id=biblioref.referencesource.874961#.Wgo8yWhSwmK

A interface está duplicando os assuntos principais:
- Bexiga Urinária Hiperativa/tratamento farmacológico
- Toxinas Botulínicas Tipo A/administração & dosagem

Já verificado no fi-admin que a indexação está ok.

**Comment by viniciusandrade** [comment]
Correção aplicada ajustando os arquivos de configuração do índice Solr e re-indexando a coleção.
