### ISSUE TITLE
Corrigir link de Inicio no site gcrhs

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/bibliographic-wp-plugin#41]
http://sites.bvsalud.org/gcrhs/
O link do breadcrumb Inicio está com link errado. Está indo para http://sites.bvsalud.org/repositorio ao invés de ir para http://sites.bvsalud.org/gcrhs/

**Comment by viniciusandrade** [comment]
Ajuste realizado pelas configurações do plugin.
