### ISSUE TITLE
Incluir lastBuildDate no elemento channel e pubdate no elemento item - RSS

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/bibliographic-wp-plugin#42]
Apesar dos elementos lastBuildDate e pubDate não serem obrigatórios, a ausência dos mesmos está afetando os agregadores de RSS no momento de ordenar os items.

Incluir elemento <lastBuildDate> no elemento <channel> e <pubDate> no elemento <item>. O lastBuildDate é sempre a data corrente e o pubDate a data de publicação no FI-Admin.

Ambos possuem o seguinte formato: "Thu, 27 Apr 2006 00:00:00 UTC", máscara "D, d M Y H:i:s T".

**Comment by viniciusandrade** [comment]
Ajuste realizado em https://github.com/bireme/bibliographic-wp-plugin/commit/10bd6977b029672e5ed3ed05800e5258f0c0fd7f
