### ISSUE TITLE
Corrigir link do item no RSS

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/bibliographic-wp-plugin#43]
No RSS está http://sites.bvsalud.org/redetsa/brisa/resource/905160

e deveria ser http://sites.bvsalud.org/redetsa/brisa/resource/?id=biblioref.referencesource.905160

**Comment by viniciusandrade** [comment]
Corrigido em https://github.com/bireme/bibliographic-wp-plugin/commit/a7e43e500410dacbd886de7f4eb206c751efa0ad
