### ISSUE TITLE
A palavra Início criada na página está com a grafia errada, o acento está no primeiro i (Ínicio) e o correto é no segundo (Início)

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bibliographic-wp-plugin#46]
Ajustar no plugin, recebido via ocomon [5664]

![image](https://user-images.githubusercontent.com/10047460/44930900-398a3c00-ad36-11e8-923b-f2a015e0805a.png)

**Comment by viniciusandrade** [comment]
@marcoslmori 

Tradução corrigida. Favor atualizar na instância informada via ocomon.
