### ISSUE TITLE
Estruturar a visualização do campo resumo da mesma forma que no portal de pesquisa da BVS

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/bibliographic-wp-plugin#47]
Exemplo de resumo estruturado com múltiplos idiomas:

http://pesquisa.bvsalud.org/portal/resource/pt/biblio-882179

Depende de https://github.com/bireme/fi-admin/issues/643

**Comment by viniciusandrade** [comment]
@cordeirofilho 

Considerar o elemento **abstract_language** para mostrar o resumo nos diferentes idiomas separados por abas. O identificado do idioma se encontra no início do elemento antes do caracter "|" pipe.

**Comment by cordeirofilho** [comment]
@viniciusandrade 
Considerei no código os idiomas Portugues (pt), Espanhol (es), Inglês (en) e Frances (fr),  tem mais algum idioma dos textos ?

**Comment by viniciusandrade** [comment]
@cordeirofilho 
Os principais são estes mesmos, conforme demanda adicionamos novos. 
Estou encerrando pois o código foi incorporado via pull request. 

Obrigado.
