### ISSUE TITLE
Apresentar no plug-in bibliographic os registros com status LILACS-Express e Migração

### ISSUE THREAD

**Issue by suelisuga** [bireme/bibliographic-wp-plugin#59]
Prezados,

Conforme acordado solicito inclusão de registros com status LILACS-Express e Migração, ademais do status "Publicado" no plug-in Bibliographic.

Muito obrigada!
Sueli

**Comment by viniciusandrade** [comment]
Os status LILACS-Express e Migração foram incluídos na recuperação do plugin.
