### ISSUE TITLE
Revisar os metadados utilizados na chamada do webservice de relacionados

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/bibliographic-wp-plugin#70]
Priorizar título e descriptores DeCS/MeSH

**Comment by wilsonmoura** [comment]
Trocar concatenação do Descritor Secundário pelo Descritor Primário

**Comment by wilsonmoura** [comment]
Realizado em 8d48611f7a8bbadd184e450fe9f0c72d864eba61
