### ISSUE TITLE
Disponibilizar no plugin a visualização do campo de titulo traduzido na referencia curta e detalhada.

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bibliographic-wp-plugin#72]
Solicitação original foi feito para a base de dados PIE, analisar se é possível especializar ou generalizar. 
Chamado original ocomon [6890] 
----
Solicito disponibilizar na interface pública da BD PIE o metadado título traduzido para o inglês, disponível no FI admin.

**Comment by viniciusandrade** [comment]
Implementado de forma geral no plugin. 

Atualizado para validação para a base PIE com a atualização do plugin.

![image](https://github.com/bireme/bibliographic-wp-plugin/assets/349287/4d63831f-f6a6-4ca0-9cd2-801dfe6aae7f)

Para as demais bases é necessário solicitar a atualização do plugin e provavelmente a re-indexação da base para que o novo campo fique disponível.
