### ISSUE TITLE
Preenchimento do campo "Código Google Analytics" dos plugins desenvolvidos pela BIREME

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bibliographic-wp-plugin#73]
É possível que os plugins desenvolvidos pela BIREME busque o ID do plugin Google Analytics Dashboard Plugin for WordPress by MonsterInsights instalado no wordpress para monitoração de acesso?.  OU caso isso não possa ser implementado, fica como protocolo oficial validado que na instalação de todos os plugins da BIREME sejam preenchidos no campo "Código Google Analytics" o mesmo id que vai no plugin do google analytics do wordpress?

**Comment by marcoslmori** [comment]
Fica aqui documentado que todos os plugins desenvolvidos pela BIREME devem ter o campo de google analytics  preenchidos  com os mesmos ids dos sites principais.  Informação definida pelo @renatomurasaki

**Comment by renatomurasaki** [comment]
O motivo é evitar a dispersão dos dados estatísticos. Aqueles que já tem ID independente manter para não prejudicar as análises atuais.
Cuidado com a aplicação da regra geral: sites.bvsalud.org apesar de serem plug-ins, são sites independentes, o que está bem o uso de ID GA diferentes.

**Comment by marcoslmori** [comment]
OK, planejamento feito para  revisar todos os plugins desenvolvidos pela BIREME nas instancias prioritárias e mais utilizadas

**Comment by viniciusandrade** [comment]
Dificilmente teríamos como buscar este ID automáticamente de outro plugin por dois pontos:

- Não criar dependência em  nossos plugins de plugins de terceiros
- Para casos onde a instalação do plugin foi feita em um sub-portal com certeza não seria possível buscar esta informação no portal principal pois se trataría de instalações independentes de WP.

**Comment by renatomurasaki** [comment]
@viniciusandrade acho que estamos falando de coisas diferentes. Não há mudança nos plug-ins, apenas a boa prática de adotar o mesmo ID da instância mãe no momento de informar o código GA no sub-site.

**Comment by viniciusandrade** [comment]
Opa @renatomurasaki, 

Meu comentário esta relacionado ao questionamento inicial do issue: "É possível que os plugins desenvolvidos pela BIREME busque o ID do plugin Google Analytics Dashboard Plugin for WordPress by MonsterInsights instalado no wordpress para monitoração de acesso?"

**Comment by renatomurasaki** [comment]
@viniciusandrade entendi... não solicitei isso, acho que foi ideia no @marcoslmori. Concordo contigo e pensei inicialmente em processo / procedimento e não automatico, até porque há exceções, como é o caso do sites.bvsalud.org que mencionei anteriormente.

**Comment by viniciusandrade** [comment]
:+1:

**Comment by marcoslmori** [comment]
documentando:  
plugins que devem ser ajustados: 
- OER
- FI-MULTIMEDIA
- BIBLIOREF
- LEISREF
- DIREVE
- LIS

BVS-Site não deve ser adicionado o número do google analytics
a partir da reunião feita em 26/05/2020 com vinicius e wilson

**Comment by viniciusandrade** [comment]
Issue fechado pois foi definido como boa prática a adoção do mesmo ID da instância mãe no momento de informar o código GA no sub-site.
