### ISSUE TITLE
Incluir texto sobre COVID e disclaimer acima da caixa de busca do site do BRISA

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/bibliographic-wp-plugin#74]
https://sites.bvsalud.org/redetsa/brisa/

[texto BRISA COVID-19.docx](https://github.com/bireme/bibliographic-wp-plugin/files/4656526/texto.BRISA.COVID-19.docx)

Inserir o texto contido no Word nos 4 idiomas do site. O disclaimer pode ir com um tamanho de letra menor do que o texto sobre COVID.

Gerar link no texto "Encontrará en esta sección los informes de ETS" com a respectiva URL

https://sites.bvsalud.org/redetsa/brisa/?lang=es&sort=&format=summary&count=10&page=1&q=covid-19+or+sars+or+sars-cov

No disclaimer, o link Termos e Condições de Uso vai para a URL já existente.

**Comment by viniciusandrade** [comment]
@renatomurasaki,
Textos adicionados no site.

Favor, quando possível, validar e se estiver OK fechar o issue.

Obrigado.

**Comment by renatomurasaki** [comment]
@viniciusandrade Obrigado! Alguns ajustes em todos os idiomas:

1) Substituir  `(...) el punto de vista de OPS` por `(...) el punto de vista de OPS/OMS`
2) Substituir `OPS / BIREME / BRISA no ofrece garantías ni responderá por la exactitud o veracidad de la información, productos, servicios y/o herramientas proporcionados en la plataforma.` por `OPS/OMS y su Centro Especializado BIREME no ofrecen garantías ni responderán por la exactitud o veracidad de la información, productos, servicios y/o herramientas proporcionados en la plataforma de BRISA.` 
3) Substituir `En ningún caso OPS/BIREME/BRISA será responsable (...)` por `En ningún caso OPS/OMS y su Centro Especializado BIREME serán responsables (...)`
4) Aumentar um pouco mais o texto sobre COVID-19. Acho que poderia deixar a segunda frase na mesma linha para diminuir o consumo de espaço

**Comment by viniciusandrade** [comment]
@renatomurasaki,

Ajustes realizados no texto. 

O texto do item 2 ficou ```OPS/OMS y su Centro Especializado BIREME no ofrece garantías ni responderá por la exactitud o veracidad de la información, productos, servicios y/o herramientas proporcionados.``` para compatibilizar com os outros idiomas que não possuem o trecho final ``` plataforma ```

Caso seja necessário ajustes menores no texto sugiro informar que pode ser feito diretamente pela opção de widgets do wp-admin.

**Comment by renatomurasaki** [comment]
Vini, por favor corrigir a concordância dos verbos ... no **ofrecen** garantías ni **responderán**, como estava no comentário https://github.com/bireme/bibliographic-wp-plugin/issues/74#issuecomment-632260634

**Comment by viniciusandrade** [comment]
Ajustes realizados.

**Comment by renatomurasaki** [comment]
@viniciusandrade faltou ajustar a concordância do inglês, de makes para make

**Comment by viniciusandrade** [comment]
Alterado no inglês makes para make.
