### ISSUE TITLE
Base PIE: customização para retirar o valor "Ministério da Saúde do Brasil" do cluster "Coleções"

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/bibliographic-wp-plugin#76]
https://sites.bvsalud.org/pie/

Há documetos indexados tanto na base PIE como na base BRISA. O que ocorre é que a marcação de coleções na BRISA está interferindo na PIE e por isso a necessidade de excluir o valor "Ministério da Saúde do Brasil" do cluster "Coleções", via camada de visualização.

NOTA: Pretende-se evitar esta situação no futuro próximo, com o uso das comunidades/coleções implementadas no âmbito do e-BlueInfo.

**Comment by viniciusandrade** [comment]
Ajuste realizado de forma hard-code no template.
