### ISSUE TITLE
Site https://sites.bvsalud.org/redetsa/brisa/ não está mostrando novos registros

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/bibliographic-wp-plugin#78]
@marcoslmori a base mostra 2066 informes. No FI-Admin há pelo menos 2077 informes indexados no BRISA com status de Publicado. Por favor verificar o que ocorre.

**Comment by viniciusandrade** [comment]
@renatomurasaki esta relacionado ao issue https://github.com/bireme/fi-admin/issues/1196 ... estou migrando todas as buscas para o novo índice Solr mas estou tendo problemas para estabilizar o serviço devido a ajustes de memória e re-indexação das coleções.

**Comment by viniciusandrade** [comment]
@renatomurasaki índice de busca atualizado, total disponível de 2112 registros.

https://sites.bvsalud.org/redetsa/brisa/

**Comment by renatomurasaki** [comment]
@viniciusandrade obrigado. Creio que há solucionado, pois FI-Admin mostra a mesma qtde do site público neste momento: 2114
