### ISSUE TITLE
Tradução dos valores de listas controladas (ex. idioma, base de dados)

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/bibliographic-wp-plugin#8]
Verificar melhor forma para a tradução dos itens que são gerenciadas como listas controladas no FI-ADMIN.

**Comment by renatomurasaki** [comment]
@viniciusandrade este issue tem relação com a falta de tradução dos clusters idioma e tipo de publicação no plug-in?

**Comment by viniciusandrade** [comment]
Ajustes realizados em https://github.com/bireme/bibliographic-wp-plugin/commit/084a1a979e8bd719abb0f45a02eb0150bcb7fe1d
