### ISSUE TITLE
Mudança de label do cluster Tipo de publicação

### ISSUE THREAD

**Issue by suelisuga** [bireme/bibliographic-wp-plugin#82]
Solicito correção do label (e possivelmente do código do campo) Tipo de publicação para Tipo de documento assim como já adotado em outras interfaces de pesquisa.

CNS:
![image](https://user-images.githubusercontent.com/13105683/120835673-01456700-c53b-11eb-9f82-f5eff4008aa3.png)

Portal Regional da BVS:
![image](https://user-images.githubusercontent.com/13105683/120835907-55504b80-c53b-11eb-91bc-45b41719f3d5.png)

Para esclarecimento, o termo Tipo de Publicação é utilizado para o ensaios clínicos, estudos de avaliação, revisão, etc.

O que é definido pelos campos 5 e 6 (tipo de literatura e nível de tratamento) tem sido usado o termo "Tipo de documento".

Muito obrigada!]
Sueli

**Comment by viniciusandrade** [comment]
@suelisuga ajuste realizado no plugin. 

Este ajuste só irá valer para novas instalações do plugin, para os sites onde o plugin já esta instalado se houver necessidade por favor solicitar a alteração da tradução pontualmente ao suporte BVS pelo Ocomon.

Obrigado
