### ISSUE TITLE
País de publicação e Idioma com dados separados?

### ISSUE THREAD

**Issue by suelisuga** [bireme/bibliographic-wp-plugin#83]
Informo que o cluster de País de publicação está aparecendo com os dados separados.

Não consegui identificar o motivo...

![image](https://user-images.githubusercontent.com/13105683/120839478-5c795880-c53f-11eb-9528-8db279ce2ec5.png)

Erro encontrado no plugin do projeto CNS, PIE e CONASS do Fi-View: https://fi-view.bvsalud.org/

![image](https://user-images.githubusercontent.com/13105683/120839794-c134b300-c53f-11eb-93f8-5724e9ca2997.png)

Muito obrigada!
Sueli

**Comment by suelisuga** [comment]
Campo Idioma com a mesma ocorrência de divisão dos conteúdos.
![image](https://user-images.githubusercontent.com/13105683/120839922-f3461500-c53f-11eb-9458-65e35d8eb16a.png)

**Comment by viniciusandrade** [comment]
@suelisuga dados dos filtros normalizados.

**Comment by suelisuga** [comment]
Ok! Revisado. Problema resolvido.

Muito obrigada!

Sueli Mitiko Yano Suga

Supervisora, Fontes de Informação Referenciais/Produção de Fontes de Informação

Centro Latino-Americano e do Caribe de Informação em Ciências da Saúde - BIREME

OPAS/OMS | Tel +55 11 5576-9831 VOIP 44831

<http://www.youtube.com/channel/UCbFox-neV7EwiFWFZViI2TQ>

[cid:32c7594a-a31a-4736-8436-140ae728d4e6]
LILACS 35 años
https://lilacs.bvsalud.org/35anos/es/
[cid:5dd8be99-de87-47b2-8815-cef71e1c6c7c]
________________________________
De: viniciusandrade ***@***.***>
Enviado: miércoles, 9 de junio de 2021 12:09
Para: bireme/bibliographic-wp-plugin ***@***.***>
Cc: Suga, Sueli Mitiko Yano (BIR) ***@***.***>; Mention ***@***.***>
Asunto: Re: [bireme/bibliographic-wp-plugin] País de publicação e Idioma com dados separados? (#83)


@suelisuga<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsuelisuga&data=04%7C01%7Csugasuel%40paho.org%7C858e4a88fac34e94641108d92b589ea4%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637588481892065612%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZzNV15qjGxDW%2FhUZNdqx718lkcHEkxoOvRn5TRDvyLE%3D&reserved=0> dados dos filtros normalizados.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fbibliographic-wp-plugin%2Fissues%2F83%23issuecomment-857784969&data=04%7C01%7Csugasuel%40paho.org%7C858e4a88fac34e94641108d92b589ea4%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637588481892075603%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MwlUOc0IJHf2isJnY9o%2BKa00J6YhvuhuFFgWNHsLTZk%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADD7UE2M5TUITL4RHZB5YHLTR573VANCNFSM46DGGHXQ&data=04%7C01%7Csugasuel%40paho.org%7C858e4a88fac34e94641108d92b589ea4%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637588481892085599%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MPRiLZ4i1ujxTV7LzJgHwMltXNxNKS5f%2BreBH9JeeD8%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by suelisuga** [comment]
@viniciusandrade ocorrência do mesmo problema no plug-in de produção da BIGG: https://sites.bvsalud.org/bigg/biblio/
![image](https://user-images.githubusercontent.com/13105683/121583746-03aa3400-ca07-11eb-94fd-04a6a7a66d40.png)

Muito obrigada!

**Comment by viniciusandrade** [comment]
@suelisuga OK, obrigado ... correção aplicada.
