### ISSUE TITLE
Implantar na visualização do registro detalhado, informações sobre recursos relacionados

### ISSUE THREAD

**Issue by suelisuga** [bireme/bibliographic-wp-plugin#87]
Implantar na visualização do rgistro detalhado, informações sobre recursos relacionados

- Incluir Tipo de relacionamento
- Título do documento
- Link, sempre que o registro não exista no FI-Admin.

Exemplo fictício:

![image](https://user-images.githubusercontent.com/13105683/165151111-fc1d9b83-62fc-4c75-a358-45f196469d34.png)

Registro não mostrou nenhuma informação do relacionamento:
![image](https://user-images.githubusercontent.com/13105683/165151326-6401af57-efb3-46bd-8a5f-c97552bb6849.png)
Ref: https://github.com/bireme/fi-admin/issues/1278

Exemplo esperado no plug-in de registros bibliográficos:
![image](https://user-images.githubusercontent.com/13105683/165151984-c854f56c-5b6d-4f7e-96cf-dd41566e0203.png)

Obrigada!

**Comment by viniciusandrade** [comment]
Exemplo disponível em:

https://fi-view.bvsalud.org/lilacs/biblio/resource/?id=biblioref.referencesource.1366689

**Comment by viniciusandrade** [comment]
Implementado no plugin e atualizado instância fi-view para validação.
