### ISSUE TITLE
Implantar na visualização do registro detalhado, informações sobre dados de pesquisa

### ISSUE THREAD

**Issue by suelisuga** [bireme/bibliographic-wp-plugin#88]
Implantar na visualização do rgistro detalhado, informações sobre recursos relacionados

- Link para dados de pesquisa
- Título do conjunto de dados
- Descrição

![image](https://user-images.githubusercontent.com/13105683/165532521-fa1994af-c7f3-4ed5-ac8c-b798d337b3f2.png)

Ref #87 Seguir modelo de documentos relacionados.

Obrigada!

**Comment by viniciusandrade** [comment]
Exemplo disponível em:

https://fi-view.bvsalud.org/lilacs/biblio/resource/?id=biblioref.referenceanalytic.1368299

**Comment by viniciusandrade** [comment]
Implementado no plugin e atualizado instância fi-view para validação.
