### ISSUE TITLE
resultado do plugin configurado para a RSDM não é o que está no fi-admin

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bibliographic-wp-plugin#90]
![image](https://user-images.githubusercontent.com/10047460/182212134-98159c66-1934-478a-9fb3-8de0ea35a182.png)

Mostram publicados:  939 registros

Analisando no FI-admin
TOTAL GERAL:   995
sendo
55 draft
4 refused
7 deletados
928 publicados

Pelo que eu entendo deve estar publicados somente os 928 publicados.  

Por favor, analisar 

Abraços. 

Mori

**Comment by marcoslmori** [comment]
exemplo https://mocambique.teste.eportuguese.org/biblio

**Comment by viniciusandrade** [comment]
@marcoslmori base de dados foi reindexada, favor solicitar validação.

**Comment by marcoslmori** [comment]
Ok, validado
