### ISSUE TITLE
Reindexar a base de dados do plugin para atualizar os dados da instância da BVS Moçambique

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bibliographic-wp-plugin#94]
https://mocambique.teste.eportuguese.org/biblio

Filtro do plugin na instancia da BVS Moçcambique:  indexed_database:"RSDM"

temos 962 registros 

No iahx:   https://pesquisa.bvsalud.org/mocambique/?u_filter%5B%5D=collection_mocambique&u_filter%5B%5D=mj_cluster&u_filter%5B%5D=type_of_study&u_filter%5B%5D=la&fb=&lang=pt&skfp=true&where=&filter%5Bcollection_mocambique%5D%5B%5D=RSDM&range_year_start=&range_year_end=
931 registros 

É reindexado diariamente. 

No fi-admin  935 registros (10/04/2023)
![image](https://user-images.githubusercontent.com/10047460/231188077-f3cb9aac-3434-46b1-80f8-ab245ac9b029.png)

**Comment by viniciusandrade** [comment]
@marcoslmori base reindexada. Total disponível pelo plugin 937.

Favor atualizar o plugin para que os valores do filtro assuntos referentes a descrtores não existentes possam ser omitidos da visualização.

Obrigado

**Comment by marcoslmori** [comment]
Ok, plugin atualizado.
