### ISSUE TITLE
Aumentar quantidade de ocorrências nos clusters

### ISSUE THREAD

**Issue by suelisuga** [bireme/bibliographic-wp-plugin#96]
A quantidade de ocorrências atualmente é de 20 opções, porém torna-se insuficiente para mostrar total ou subtotal de ocorrências.

Algumas opções seria possibilitar definir a quantidade de ocorrências necessárias na área de configuração do plug-in ou incluir um "Mostrar mais", assim como ocorre no iAHx.

Justificativa: Melhorar recuperação baseada em navegação nos clusters.
Requisição foi feita após feedback de coordenação de BVS (Vet)

Obrigada!

**Comment by wilsonmoura** [comment]
@suelisuga ajustes realizados. Favor validar.

**Comment by suelisuga** [comment]
oi @wilsonmoura para eu validar eu preciso do @marcoslmori  não é? Ele precisa atualizar a instancia de testes para eu poder revisar. Vou aguardar ele atualizar para poder validar. Obrigada!
