### ISSUE TITLE
Incluir opção de ordenação dos registros por data de publicação, data de registro e relevância

### ISSUE THREAD

**Issue by suelisuga** [bireme/bibliographic-wp-plugin#97]
Solicito incluir funcionalidade de ordenação dos registros por data de publicação, data de registro e relevância, assim como existente no iAHx.

Justificativa: 
-facilitar visualização e navegação pelos usuários
-padronizar plug-ins de fontes de informação

Solicitação realizada por coordenação de BVS (Vet)

Obrigada!

**Comment by wilsonmoura** [comment]
@suelisuga ajustes realizados. Favor validar.
