### ISSUE TITLE
Mostrar descritor e recuperar registros representados por ele

### ISSUE THREAD

**Issue by suelisuga** [bireme/bibliographic-wp-plugin#98]
Considerando descritores atualizados ou excluidos, solicito que:
Texto do descritor seja apresentado
Documentos indexados sejam apresentados como resultado

Atualmente aparecem como número do ID:

![image](https://user-images.githubusercontent.com/13105683/235767671-2ffb2e89-1277-46d1-9dd3-b966f21879a4.png)

E lista de registros não é apresentada:
![image](https://user-images.githubusercontent.com/13105683/235768404-cb217e76-eae0-431f-ae08-be7bdd6d8608.png)

Muito obrigada!

**Comment by viniciusandrade** [comment]
Ajuste realizado no plugin para não mostrar os ID's dos descritores eliminados do DeCS,  mesmo caso já tratado em https://github.com/bireme/fi-multimedia-wp-plugin/issues/6.

Adicionalmente foi atualizado o plugin na instância fi-view.bvsalud.org
