### ISSUE TITLE
Possibilitar escolher a forma de ordenar o cluster

### ISSUE THREAD

**Issue by suelisuga** [bireme/bibliographic-wp-plugin#99]
Solicito incluir possibilidade de ordenar o cluster conforme a necessidade do usuário.

Exemplo: ordenar cluster por ano de publicação e  não por ocorrências.
![image](https://user-images.githubusercontent.com/13105683/235769329-ee20baf6-ba2f-439f-be63-9c5a49d2a272.png)

Exemplo: País por ordem alfabética e não por ocorrência
![image](https://user-images.githubusercontent.com/13105683/235769570-e38187fa-f38d-4f73-9572-93377616537c.png)

Justificativa: melhorar navegação e recuperação específica por opções dos clusters

Necessidade identificada por coordenação de BVS

Obrigada

**Comment by wilsonmoura** [comment]
@suelisuga ajustes realizados. Favor validar.
